import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Exo } from "next/font/google";
import Navbar from "./_components/Navbar";
import Footer from "./_components/Footer";
import TopNavbar from "./_components/topNavbar";
import MySessionProvider from "./_providers/MySessionProvider";
import CartContextProvider from "./_context/cartContextProvider";
import { getUserCart } from "./_actions/cart.actions";
import { ToastContainer } from "react-toastify/unstyled";
import WishlistProvider from "./_context/wishListContextProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const exo = Exo({
  subsets: ["latin"],
  variable: "--font-exo",
  weight: ["400", "500", "600", "700"], 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {

const userCart = await getUserCart()

// console.log(userCart.data.products,"userCart");





  return (
    <html
      lang="en"
      className={` ${exo.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-white ">

        <MySessionProvider>
          <WishlistProvider>
          <CartContextProvider userCart = {userCart}>
            <ToastContainer/> 
        <TopNavbar/>
          <Navbar />
          {children}
          <Footer/>
          </CartContextProvider>
          </WishlistProvider>
        </MySessionProvider>

      </body>
    </html>
  );
}
